SELECT YEAR(SALES_DATE) YEAR
     , MONTH(SALES_DATE) MONTH
     , GENDER
     , COUNT(DISTINCT S.USER_ID) USERS
FROM   USER_INFO U
JOIN   ONLINE_SALE S
ON     U.USER_ID = S.USER_ID
WHERE  U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;