SELECT LEFT(A.SALES_DATE, 10) SALES_DATE
     , A.PRODUCT_ID
     , A.USER_ID
     , SUM(A.SALES_AMOUNT) SALES_AMOUNT
FROM (
    SELECT SALES_DATE
         , PRODUCT_ID
         , USER_ID
         , SALES_AMOUNT
    FROM   ONLINE_SALE
    UNION
    SELECT SALES_DATE
         , PRODUCT_ID
         , NULL
         , SALES_AMOUNT
    FROM   OFFLINE_SALE) A
WHERE  A.SALES_DATE LIKE '2022-03%'
GROUP BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID