SELECT YEAR(S.SALES_DATE) YEAR
     , MONTH(S.SALES_DATE) MONTH
     , COUNT(DISTINCT U.USER_ID) PUCHASED_USERS
     , ROUND(COUNT(DISTINCT U.USER_ID) / (
                SELECT COUNT(DISTINCT USER_ID)
                FROM   USER_INFO
                WHERE  JOINED LIKE '2021%'), 1) PUCHASED_RATIO
FROM   USER_INFO U
JOIN   ONLINE_SALE S
ON     U.USER_ID = S.USER_ID
WHERE  U.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH