SELECT OUTS.ANIMAL_ID
     , OUTS.ANIMAL_TYPE
     , OUTS.NAME
FROM   ANIMAL_INS INS
JOIN   ANIMAL_OUTS OUTS
ON     INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE  LEFT(INS.SEX_UPON_INTAKE, 6) = 'Intact'
AND   (LEFT(OUTS.SEX_UPON_OUTCOME, 6) = 'Spayed'
OR     LEFT(OUTS.SEX_UPON_OUTCOME, 8) = 'Neutered')
ORDER BY OUTS.ANIMAL_ID;