SELECT DATE_FORMAT(START_DATE, '%c') MONTH
     , CAR_ID
     , COUNT(HISTORY_ID) RECORDS
FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE  LEFT(START_DATE, 7) BETWEEN '2022-08' AND '2022-10'
AND    CAR_ID IN (
        SELECT CAR_ID
        FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE  LEFT(START_DATE, 7) BETWEEN '2022-08' AND '2022-10'
        GROUP BY CAR_ID
        HAVING COUNT(HISTORY_ID) >=5)
GROUP BY MONTH, CAR_ID
HAVING  RECORDS > 0
ORDER BY DATE_FORMAT(START_DATE, '%m'), CAR_ID DESC