SELECT USER_ID
     , NICKNAME
     , CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소
     , CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 12)) 전화번호
FROM   USED_GOODS_BOARD BRD
JOIN   USED_GOODS_USER USR
ON     BRD.WRITER_ID = USR.USER_ID
GROUP BY BRD.WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY USR.USER_ID DESC;