SELECT USR.USER_ID, USR.NICKNAME, SUM(BRD.PRICE) TOTAL_SALES
FROM   USED_GOODS_BOARD BRD
JOIN   USED_GOODS_USER USR
ON     BRD.WRITER_ID = USR.USER_ID
WHERE  BRD.STATUS = 'DONE'
GROUP BY USR.USER_ID
HAVING SUM(BRD.PRICE) >= 700000
ORDER BY TOTAL_SALES;