SELECT PRF.MEMBER_NAME
     , RVW.REVIEW_TEXT
     , DATE_FORMAT(RVW.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM   MEMBER_PROFILE PRF
JOIN   REST_REVIEW RVW
ON     PRF.MEMBER_ID = RVW.MEMBER_ID
WHERE  RVW.MEMBER_ID = (
        SELECT MEMBER_ID
        FROM   REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
        LIMIT  1)
ORDER BY REVIEW_DATE, RVW.REVIEW_TEXT;