SELECT PRD.PRODUCT_ID
     , PRD.PRODUCT_NAME
     , SUM(PRD.PRICE * ORD.AMOUNT) TOTAL_SALES
FROM   FOOD_PRODUCT PRD
JOIN   FOOD_ORDER ORD
ON     PRD.PRODUCT_ID = ORD.PRODUCT_ID
WHERE  LEFT(ORD.PRODUCE_DATE, 7) = '2022-05'
GROUP BY PRD.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRD.PRODUCT_ID;