SELECT INF.REST_ID
     , INF.REST_NAME
     , INF.FOOD_TYPE
     , INF.FAVORITES
     , INF.ADDRESS
     , ROUND(AVG(RVW.REVIEW_SCORE), 2) SCORE
FROM   REST_INFO INF
JOIN   REST_REVIEW RVW
ON     INF.REST_ID = RVW.REST_ID
WHERE  LEFT(INF.ADDRESS, 2) = '서울'
GROUP BY INF.REST_ID
ORDER BY SCORE DESC, INF.FAVORITES DESC;